name: PR Execute UT

on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"

jobs:
  execute-ut:
    name: Executing UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Executing unit tests
        run: ./build.cmd ExecuteUnitTests
