name: PR Execute UT

on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  execute-ut:
    name: Execute UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run './build.cmd ExecuteUnitTests'
        run: ./build.cmd ExecuteUnitTests