name: PR_Execute_DOTNET_UT

on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  execute-ut:
    name: Execute UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd ExecuteUnitTests'
        run: ./build.cmd ExecuteUnitTests
