name: PR Merged to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release-new-version:
    name: Create a Release when a PR is merged
    runs-on: release-new-version
    steps:
      - uses: actions/checkout@v2
      - name: Calculate Next Release Number, Update Version In Files, Push Changes
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CalculateNextReleaseNumber UpdateVersionInFiles UpdateChangelog GitPushReleaseFiles
      - name: Dotnet Publish
        run: ./build.cmd Publish
      - name: Zipping assets
        run: ./build.cmd CompressDirectory
      - name: Create the New Release
        run: ./build.cmd CreateNewRelease --skip UpdateVersionInFiles+UpdateChangelog+GitPushReleaseFiles
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
