name: PR Merged to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release-new-version:
    name: Releasing new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculating next release number, updating version in cicd.json and adding changes to the changelog
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CalculateNextReleaseNumber UpdateVersionInCICDFile UpdateChangelog
      - name: Saving cicd.schema.json version
        run: |
          schemaVersion=$(jq -r .CalculateNextReleaseNumber cicd.resultbag.json)
          cp cicd.schema.json "./cicd.schemas/$schemaVersion.json"
      - name: Pushing changes before creating the release
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd GitPushReleaseFiles
      - name: Publishing dotnet project for release assets
        run: ./build.cmd Publish
      - name: Zipping release assets
        run: ./build.cmd CompressDirectory
      - name: Creating the New Release
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CreateNewRelease --skip ListCommitsInThisPR
