name: PR_MERGED_RELEASE_NEW_VERSION

on:
  push:
    branches:
      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Parse Last Commit to Convention Commit
        run: ./build.cmd GetLastConventionCommit
      # - name: Calculate Next Release Number, Update Version In Files, Push Changes
      #   run: ./build.cmd CalculateNextReleaseNumber UpdateVersionInFiles GitPush
      # - name: Publish Dotnet Core and Zip the output
      #   run: ./build.cmd Publish CompressDirectory
      # - name: Publish Create a New Release
      #   run: ./build.cmd CreateNewRelease
      #   env:
      #     GitHubToken: ${{ secrets.GITHUB_TOKEN }}
