name: PR_MERGED_PRINT_PIPE_INFO

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Print Execution Info
        run: ./build.cmd PrintPipelineInfo
      - name: List Commits in the PR Merged
        run: ./build.cmd GetCommitsInAMergedPR
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}