name: PR_MERGED_RELEASE_NEW_VERSION

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Calculate Next Release Number, Update Version In Files, Push Changes
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CalculateNextReleaseNumber UpdateVersionInFiles GitPush
      - name: Dotnet Publish
        run: dotnet publish ./src/cangulo.cicd/cangulo.cicd.csproj  -o ./artifacts/cangulo.cicd/ -r linux-x64 --self-contained
      - name: Zip assets
        run: |
          mkdir releaseAssets
          zip -j -r ./releaseAssets/cangulo.cicd-linux-x64.zip ./artifacts/cangulo.cicd/
      # - name: Dotnet Publish and Zip the output
      #   run: ./build.cmd Publish CompressDirectory
      - name: Create the New Release
        run: ./build.cmd CreateNewRelease
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
