name: PR Merged to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release-new-version:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculate Next Release Number, Update Version In Files, Push Changes
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CalculateNextReleaseNumber UpdateVersionInCICDFile UpdateChangelog GitPushReleaseFiles
      - name: Dotnet Publish
        run: ./build.cmd Publish
      - name: Zipping assets
        run: ./build.cmd CompressDirectory
      - name: Create the New Release
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CreateNewRelease --skip ListCommitsInThisPR
