name: PR Validate Commits

on:
  pull_request:
    types: [synchronize]


jobs:
  validate-conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculate next release number
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd CalculateNextReleaseNumber 
      - name: Version cicd.json file
        run: cat cicd.resultbag.json