# name: Test

# on:
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   validate-conventional-commits:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Calculate next release number
#         env:
#           GitHubToken: ${{ secrets.GITHUB_TOKEN }}
#         run: ./build.cmd CalculateNextReleaseNumber
#       - name: get the version
#         run: |
#           schemaVersion=$(jq -r .CalculateNextReleaseNumber cicd.resultbag.json)
#           cp cicd.schema.json "./cicd.schemas/cicd.schema.$schemaVersion.json"
