name: PR Validate Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-conventional-commits:
    name: Validating Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verifying commits follow conventions defined in cicd.json
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.cmd VerifyAllCommitsAreConventionalInThisPR
